spring.application.name=${SPRING_APPLICATION_NAME:healthapp}

# PostgreSQL
spring.datasource.url=${POSTGRES_DB_URL}
spring.datasource.username=${POSTGRES_DB_USERNAME}
spring.datasource.password=${POSTGRES_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:true}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

# Flyway
spring.flyway.enabled=${FLYWAY_ENABLED:false}

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:DEBUG}

#Spring MVC
spring.mvc.time-zone=America/Jamaica

#geoapify
geoapify.api.key=d548c5ed24604be6a9dd0d989631f783


# ---------- ClickHouse ----------
# spring.datasource.clickhouse.url=jdbc:clickhouse://localhost:8123/healthcare_queue
spring.datasource.clickhouse.jdbc-url=jdbc:clickhouse:http://clickhouse:8123/healthcare_queue
spring.datasource.clickhouse.username=admin
spring.datasource.clickhouse.password=admin123

# logging.level.root=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.orm.jpa=DEBUG